/**
 * Turns out/results.json into out/summary.md. Pure formatting: every number here comes from results.json.
 *   node tests/summary.ts      regenerate the summary without re-running the measurements
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { mdTable, pct, round } from './util.ts';

type J = any; // eslint-disable-line @typescript-eslint/no-explicit-any

const MODES = ['transform', 'zoom', 'plain'];
const MODE_LABEL: Record<string, string> = {
  transform: 'transform: scale(s)',
  zoom: 'CSS zoom: s',
  plain: 'unscaled layout at final size',
};

function scalesOf(o: J): string[] {
  return Object.keys(o ?? {}).sort((a, b) => Number(a) - Number(b));
}

function f(x: unknown, d = 2): string {
  return typeof x === 'number' && Number.isFinite(x) ? String(round(x, d)) : 'n/a';
}

export function buildSummary(R: J): string {
  const out: string[] = [];
  const h = (s: string) => out.push(`\n## ${s}\n`);
  const p = (s: string) => out.push(`${s}\n`);

  out.push('# S6 measurements (generated by tests/summary.ts from out/results.json)\n');
  if (R.meta) {
    p(`Run ${R.meta.date}; ${R.meta.browser}${R.meta.headless ? ' (headless)' : ' (headed)'}; viewport ${R.meta.viewport}; Node ${R.meta.node}.`);
    p(`Packages: ${Object.entries(R.meta.packages ?? {}).map(([k, v]) => `${k} ${v}`).join(', ')}.`);
  }

  // ---------------------------------------------------------------- 1 click
  if (R.click) {
    h('1. Click-to-caret');
    p('Two real mouse clicks per glyph (at 25% and 75% of its width). "strict" = the selection is at that glyph\'s own logical start/end. "caret at clicked edge" = strict hit, or a strict miss whose caret was found painted (screenshot) at the glyph edge nearest the click.');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.click[m])) {
        const c = R.click[m][s];
        rows.push([
          MODE_LABEL[m]!,
          s,
          f(c.glyphWidthPx.mean, 1),
          pct(c.by.he.ok, c.by.he.n),
          pct(c.by.en.ok, c.by.en.n),
          pct(c.by.boundary.ok, c.by.boundary.n),
          pct(c.by.other.ok, c.by.other.n),
          pct(c.by.rot.ok, c.by.rot.n),
          pct(c.total.ok, c.total.n),
          pct(c.total.visualOk, c.total.n),
          `${c.strictMisses.atBoundary}/${c.strictMisses.n}`,
        ]);
      }
    p(mdTable(['scaling', 's', 'mean glyph px', 'Hebrew', 'English', 'bidi boundary', 'digits/punct./space', 'rotated box', 'all, strict', 'all, caret at clicked edge', 'strict misses at a boundary'], rows));
    const st = Object.entries(R.click.transform ?? {}).map(([s, c]: [string, J]) => `${s}: ${Object.values(c.dirSelfTest).reduce((a: number, x: J) => a + x.violations.length, 0)}/${Object.values(c.dirSelfTest).reduce((a: number, x: J) => a + x.pairs, 0)}`);
    p(`\nHarness self-test (glyph direction model vs real layout, violations/pairs): ${st.join(', ')}.`);
    if (R.clickPaced) {
      p(`\nPaced control (every 23rd target, 520 ms apart, ProseMirror click chain untouched): ${scalesOf(R.clickPaced.transform).map((s) => `s=${s}: ${R.clickPaced.transform[s].ok}/${R.clickPaced.transform[s].n}`).join(', ')}.`);
    }
    const ref = R.click.plain?.['1'] ?? R.click.transform?.['1'];
    if (ref) p(`\nStrict misses at s=1 without any transform (\`plain\`): \`${ref.strictMisses.list.join(' ')}\``);
    const same: string[] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.click[m])) {
        if (!ref) continue;
        const a = [...R.click[m][s].strictMisses.list].map((x: string) => x.replace('!', '')).sort().join(' ');
        const b = [...ref.strictMisses.list].map((x: string) => x.replace('!', '')).sort().join(' ');
        same.push(`${m}@${s}: ${a === b ? 'same set' : 'DIFFERENT'}`);
      }
    if (same.length) p(`\nStrict-miss set compared with that control: ${same.join(', ')}.`);
  }

  // ---------------------------------------------------------------- 2 coords
  if (R.coords) {
    h('2. Caret geometry');
    p('`coordsAtPos` against glyph rectangles (px on screen). "nearest edge" = distance to the nearer of the two glyph edges logically adjacent to the position. "side hits" = how often `coordsAtPos(pos, side)` is at the edge that `side` names. "two-place positions" = caret positions whose two sides are drawn in different places on one line (bidi) or on two lines (wrap).');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.coords[m])) {
        const c = R.coords[m][s];
        const u = c.unrotated;
        rows.push([
          MODE_LABEL[m]!,
          s,
          `${f(u.he.errEither.max)} / ${f(u.en.errEither.max)} / ${f(u.boundary.errEither.max)}`,
          f(u.all.errEither.max / Number(s), 3),
          `${u.all.primaryHits}/${u.all.n}`,
          `${u.boundary.primaryHits}/${u.boundary.n}`,
          `${u.all.ambiguousBidi} bidi, ${u.all.ambiguousWrap} wrap`,
          f(u.all.errTop.max),
          `${f(c.rotated.errEither.max)} / ${f(c.rotated.errLeft.max)}`,
          `${c.roundTrip.unrotated.exact}+${c.roundTrip.unrotated.equivalent}eq+${c.roundTrip.unrotated.mismatch}x / ${c.roundTrip.unrotated.n}`,
          `${c.roundTrip.rotated.exact}+${c.roundTrip.rotated.equivalent}eq+${c.roundTrip.rotated.mismatch}x / ${c.roundTrip.rotated.n}`,
        ]);
      }
    p(mdTable(['scaling', 's', 'nearest edge max px (he / en / boundary)', 'same, in slide px', 'side hits, all', 'side hits, boundary', 'two-place positions', 'top/bottom max px', 'rotated: centre max / `left` max px', 'posAtCoords round trip, unrotated', 'round trip, rotated'], rows));
    p('\nRound trip legend: exact + eq (another logical position drawn at the same place) + x (mismatch).');
    const mm = R.coords.plain?.['1']?.roundTripMismatches;
    if (mm) p(`\nRound-trip mismatches without any transform (plain, s=1): \`${JSON.stringify(mm.map((x: J) => `${x.id}:${x.pos}->${x.got} (${f(x.dist, 1)}px)`))}\``);
  }

  // ---------------------------------------------------------------- 3 selection
  if (R.selection) {
    h('3. Selection');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.selection[m])) {
        const c = R.selection[m][s];
        const flat = c.drags.filter((d: J) => d.id !== 'rot');
        const rot = c.drags.find((d: J) => d.id === 'rot');
        rows.push([
          MODE_LABEL[m]!,
          s,
          `${c.drags.filter((d: J) => d.ok).length}/${c.drags.length}`,
          f(Math.min(...flat.map((d: J) => d.paint.covered)) * 100, 1),
          f(Math.min(...flat.map((d: J) => d.paint.inside)) * 100, 1),
          rot ? `${f(rot.paint.inside * 100, 1)} / ${f(rot.paint.covered * 100, 1)}` : 'n/a',
          `${c.dbl.filter((d: J) => d.ok).length}/${c.dbl.length}`,
          `${c.triple.filter((d: J) => d.ok).length}/${c.triple.length}`,
        ]);
      }
    p(mdTable(['scaling', 's', 'mouse drags logically correct', 'highlight covers selection rects, min %', 'highlight inside selection rects, min %', 'rotated: inside / covered % (bounding boxes)', 'double-click word', 'triple-click paragraph'], rows));
    const c = R.selection.transform?.['0.64'];
    if (c) {
      p('\nDrag cases at transform 0.64 (selected text is in logical order):');
      p(mdTable(['case', 'box', 'ok', 'selected text', 'client rects'], c.drags.map((d: J) => [d.name, d.id, d.ok ? 'yes' : 'NO', `\`${String(d.got.text).replace(/\n/g, ' / ')}\``, d.rects])));
      p(`\nDouble-click results at transform 0.64: ${c.dbl.map((d: J) => `\`${d.word}\` -> \`${d.got}\``).join(', ')}.`);
    }
  }

  // ---------------------------------------------------------------- 4 keyboard
  if (R.keyboard) {
    h('4. Keyboard movement');
    p('Caret after every key press, as (paragraph:offset), compared with a bare `contenteditable` holding the same markup, unscaled (the native Chromium control). "same" = identical sequence.');
    const nat = R.keyboard.native?.['1'] ?? {};
    const cols: [string, J][] = [];
    for (const m of MODES) for (const s of scalesOf(R.keyboard[m])) cols.push([`${m} ${s}`, R.keyboard[m][s]]);
    const rows: (string | number)[][] = [];
    for (const name of Object.keys(nat)) {
      const refSeq = nat[name].seq.join(' ');
      rows.push([name, nat[name].seq.length, ...cols.map(([, r]) => (r[name] ? (r[name].seq.join(' ') === refSeq ? 'same' : 'DIFF') + (r[name].pmConsistent === false ? ' (PM out of sync)' : '') : 'n/a'))]);
    }
    p(mdTable(['scenario', 'keys', ...cols.map(([n]) => n)], rows));
    const nr = R.keyboard['transform-norot']?.['0.64'];
    const nn = R.keyboard['native-norot']?.['1'];
    const rotName = 'ArrowDown/Up in rotated box';
    if (nr && nn && nat[rotName]) {
      p(`\nRotated box, ArrowDown/ArrowUp/End/Home: rotated native \`${nat[rotName].seq.join(' ')}\`, rotated TipTap@0.64 \`${R.keyboard.transform?.['0.64']?.[rotName]?.seq.join(' ')}\`, same box without rotation: native \`${nn[rotName].seq.join(' ')}\`, TipTap@0.64 \`${nr[rotName].seq.join(' ')}\`.`);
    }
    p('\nNative reference sequences (what the keys do):\n');
    for (const name of Object.keys(nat)) {
      const seq: string[] = nat[name].seq;
      const shown = seq.length > 16 ? `${seq.slice(0, 7).join(' ')} ... ${seq.slice(-4).join(' ')} (${seq.length} steps, ${isMonotonic(seq)})` : seq.join(' ');
      p(`- ${name}: \`${shown}\``);
    }
  }

  // ---------------------------------------------------------------- 5 typing
  if (R.typing) {
    h('5. Typing');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.typing[m])) {
        const c: J[] = R.typing[m][s];
        rows.push([MODE_LABEL[m]!, s, `${c.filter((x) => x.ok).length}/${c.length}`, c.filter((x) => !x.ok).map((x) => x.name).join('; ') || '-']);
      }
    p(mdTable(['scaling', 's', 'checks passed', 'failed'], rows));
    const c: J[] | undefined = R.typing.transform?.['0.64'];
    if (c) p(`\nChecks: ${c.map((x) => x.name).join('; ')}.`);
    const k = c?.find((x) => x.keydowns !== undefined);
    if (k) p(`\nKey path check (first case): ${k.keydowns} keydown events and ${k.insertTextInputs} beforeinput(insertText) events for ${String(k.typed).length} typed characters.`);
  }

  // ---------------------------------------------------------------- 6 ime
  if (R.ime) {
    h('6. IME composition (CDP)');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.ime[m])) {
        const c: J[] = R.ime[m][s];
        rows.push([MODE_LABEL[m]!, s, `${c.filter((x) => x.ok).length}/${c.length}`, c.filter((x) => !x.ok).map((x) => x.name).join('; ') || '-']);
      }
    p(mdTable(['scaling', 's', 'cases passed', 'failed'], rows));
    const c: J[] | undefined = R.ime.transform?.['0.64'];
    if (c) p(`\nCases: ${c.map((x) => `${x.name} (events start/update/end ${x.events.start}/${x.events.update}/${x.events.end})`).join('; ')}.`);
  }

  // ---------------------------------------------------------------- 7 undo
  if (R.undo) {
    h('7. Undo granularity (transform 0.64)');
    const t: J[] = R.undo.tiptap ?? [];
    const e: J[] = R.undo.external ?? [];
    const n: J[] = R.undo.none ?? [];
    p(mdTable(['typing scenario', 'TipTap UndoRedo: groups', 'Ctrl+Z to restore', 'outside history: entries (PM transactions merged)', 'Ctrl+Z to restore', 'no history, no key binding: Ctrl+Z x12'], t.map((x, i) => [x.name, x.undoGroups, x.ctrlZToRestore, `${e[i]?.externalEntries} (${(e[i]?.externalTransactions ?? []).join('+')})`, e[i]?.ctrlZToRestore, typeof n[i]?.ctrlZToRestore === 'number' ? `restored after ${n[i].ctrlZToRestore}` : `document unchanged${n[i]?.domMatchesState ? ', DOM = state' : ', DOM != state'}`])));
  }

  // ---------------------------------------------------------------- 8 bubble
  if (R.bubble) {
    h('8. Bubble menu anchored to the selection');
    p('`dx` = menu centre minus selection centre (px), `gap` = distance between menu bottom and selection top (configured offset 8 px), size = on-screen size of a menu that is 112x32 px in layout. "inside" = TipTap default (menu appended next to the editor, inside the scaled slide); "body" = `appendTo: document.body`.');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.bubble[m]))
        for (const v of ['inside', 'body']) {
          const c: J[] = R.bubble[m][s][v] ?? [];
          const flat = c.filter((x) => x.id !== 'rot' && x.first);
          const rot = c.find((x) => x.id === 'rot');
          const sc = c.filter((x) => x.afterScroll);
          rows.push([
            MODE_LABEL[m]!,
            s,
            v,
            flat.length ? f(Math.max(...flat.map((x) => Math.abs(x.first.dx)))) : 'n/a',
            flat.length ? `${f(Math.min(...flat.map((x) => x.first.gap)))}..${f(Math.max(...flat.map((x) => x.first.gap)))}` : 'n/a',
            flat.length ? `${f(flat[0].first.menuW, 0)}x${f(flat[0].first.menuH, 0)}` : 'n/a',
            rot?.first ? `dx ${f(rot.first.dx)}, gap ${f(rot.first.gap)}, ${f(rot.first.menuW, 0)}x${f(rot.first.menuH, 0)}` : 'n/a',
            sc.length ? `dx ${f(Math.max(...sc.map((x) => Math.abs(x.afterScroll.dx))))}, gap ${f(Math.min(...sc.map((x) => x.afterScroll.gap)))}..${f(Math.max(...sc.map((x) => x.afterScroll.gap)))}` : 'no scroll possible',
          ]);
        }
    p(mdTable(['scaling', 's', 'menu parent', 'max |dx| px', 'gap px', 'menu size px', 'rotated box', 'after the stage scrolled'], rows));
  }

  // ---------------------------------------------------------------- 9 caret
  if (R.caret) {
    h('9. Painted caret');
    p('Screenshot difference between a red caret and a transparent caret. `peak` = strongest colour change (255 = one fully opaque caret pixel); distances are from the centre of the painted caret.');
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.caret[m])) {
        const c: J[] = R.caret[m][s];
        const flat = c.filter((x) => x.id !== 'rot');
        const clicks = c.filter((x) => x.toClickedEdge !== null);
        const edge = c.filter((x) => x.name.includes('run edge') || x.name.includes('line starts'));
        rows.push([
          MODE_LABEL[m]!,
          s,
          `${c.filter((x) => x.painted).length}/${c.length}`,
          `${f(Math.min(...flat.map((x) => x.widthPx)), 1)}..${f(Math.max(...flat.map((x) => x.widthPx)), 1)}`,
          `${Math.min(...flat.map((x) => x.peak))}..${Math.max(...flat.map((x) => x.peak))}`,
          f(Math.max(...clicks.map((x) => x.toClickedEdge))),
          f(Math.max(...c.filter((x) => !edge.includes(x)).map((x) => Math.min(x.toCoordsSide1, x.toCoordsSideMinus1)))),
          edge.map((x) => `${f(x.toCoordsSide1, 0)}/${f(x.toCoordsSideMinus1, 0)}`).join(', '),
        ]);
      }
    p(mdTable(['scaling', 's', 'caret found', 'painted width px (unrotated)', 'peak 0..255', 'click cases: max distance to clicked glyph edge px', 'non-edge cases: max distance to coordsAtPos px', 'run-edge cases: distance to coordsAtPos side 1 / side -1 px'], rows));
  }

  // ---------------------------------------------------------------- 11 lines
  if (R.lines) {
    h('10. Line breaking per scaling technique');
    p('Number of text blocks (11 in the five boxes) whose line breaks differ from the transform layout (which is the 1920x1080 layout at every scale).');
    const ref = R.lines.transform?.['1'] ?? R.lines.transform?.[scalesOf(R.lines.transform)[0]!];
    const rows: (string | number)[][] = [];
    for (const m of MODES)
      for (const s of scalesOf(R.lines[m])) {
        const cur = R.lines[m][s];
        let diff = 0;
        let total = 0;
        const which: string[] = [];
        for (const id of Object.keys(ref)) {
          ref[id].forEach((l: number[], i: number) => {
            total += 1;
            if (JSON.stringify(l) !== JSON.stringify(cur[id]?.[i])) {
              diff += 1;
              which.push(`${id}[${i}] ${JSON.stringify(l)} -> ${JSON.stringify(cur[id]?.[i])}`);
            }
          });
        }
        rows.push([MODE_LABEL[m]!, s, `${diff}/${total}`, which.join('; ') || '-']);
      }
    p(mdTable(['scaling', 's', 'text blocks that reflow', 'line-start offsets: transform -> this mode'], rows));
  }

  // ---------------------------------------------------------------- misc
  if (R.dnd) {
    h('11. Other checks');
    p(`Drag-and-drop of selected text (drop position comes from posAtCoords): ${MODES.map((m) => scalesOf(R.dnd[m]).map((s) => `${m}@${s}: ${R.dnd[m][s].ok ? 'ok' : 'FAIL'}`).join(', ')).filter(Boolean).join('; ')}.`);
  }
  if (R.scroll) {
    p(`\nscrollIntoView when typing in a box that is off screen at s=2: ${Object.keys(R.scroll).map((m) => `${m}: caret in view before ${R.scroll[m]['2'].caretInViewBefore}, after ${R.scroll[m]['2'].caretInViewAfter} (stage scroll ${JSON.stringify(R.scroll[m]['2'].stageScrollAfter)})`).join('; ')}.`);
  }
  if (R.eotb) {
    p(`\n\`view.endOfTextblock('up' | 'down')\` per visual line (expected: up only on the first line, down only on the last): ${Object.keys(R.eotb).map((k) => `${k}: ${(Object.values(R.eotb[k])[0] as J[]).map((x) => `${x.id} line ${x.line + 1}/${x.of} up=${x.up} down=${x.down}${x.ok ? '' : ' WRONG'}`).join(', ')}`).join(' | ')}.`);
  }
  if (R.focusHeuristic) {
    p('\nHome pressed shortly after the editor received focus (caret at the end of the first paragraph, expected to move to offset 0):');
    p(mdTable(['page', ...R.focusHeuristic['tiptap transform 0.64'].map((x: J) => `${x.focus}, ${x.msAfterFocus} ms`)], Object.keys(R.focusHeuristic).map((k) => [k, ...R.focusHeuristic['tiptap transform 0.64'].map((_: J, i: number) => (R.focusHeuristic[k][i] ? (R.focusHeuristic[k][i].ok ? 'moved' : `stayed at ${R.focusHeuristic[k][i].caretOffsetAfterHome}`) : 'n/a'))])));
  }
  if (R.listdir) {
    p('\nList item direction (computed `direction` of li / p / ul for the three items: Hebrew, Hebrew with English, English with Hebrew):');
    p(mdTable(['where `dir` lives', 'item 1', 'item 2', 'item 3'], Object.keys(R.listdir).map((k) => [k, ...R.listdir[k]])));
  }
  if (R.trailing) {
    p(`\nStarterKit TrailingNode on a text box that ends with a list: ${Object.keys(R.trailing).map((k) => `${k}: empty paragraph appended after typing = ${R.trailing[k].endsWithEmptyParagraphAfterTyping} (\`${R.trailing[k].tail}\`)`).join('; ')}.`);
  }

  // ---------------------------------------------------------------- dsf
  if (R.dsf15) {
    h('12. deviceScaleFactor 1.5 (Windows display scaling 150%), transform only');
    const rows: (string | number)[][] = [];
    for (const s of scalesOf(R.dsf15.click)) {
      const c = R.dsf15.click[s];
      const g = R.dsf15.coords[s];
      const k: J[] = R.dsf15.caret[s];
      const flat = k.filter((x) => x.id !== 'rot');
      rows.push([s, pct(c.total.ok, c.total.n), pct(c.total.visualOk, c.total.n), f(g.unrotated.all.errEither.max), `${g.roundTrip.unrotated.exact}+${g.roundTrip.unrotated.equivalent}eq+${g.roundTrip.unrotated.mismatch}x / ${g.roundTrip.unrotated.n}`, `${f(Math.min(...flat.map((x) => x.widthPx)), 1)}..${f(Math.max(...flat.map((x) => x.widthPx)), 1)}`, `${Math.min(...flat.map((x) => x.peak))}..${Math.max(...flat.map((x) => x.peak))}`]);
    }
    p(mdTable(['s', 'click strict', 'click, caret at clicked edge', 'coordsAtPos nearest edge max px', 'round trip, unrotated', 'caret width CSS px', 'caret peak'], rows));
  }
  return out.join('\n');
}

function isMonotonic(seq: string[]): string {
  const offs = seq.map((x) => Number(x.split(':')[1]));
  const up = offs.every((v, i) => i === 0 || v === offs[i - 1]! + 1);
  const down = offs.every((v, i) => i === 0 || v === offs[i - 1]! - 1);
  return up ? 'offset +1 every key' : down ? 'offset -1 every key' : 'not monotonic';
}

export function writeSummary(results: Record<string, unknown>, file: string) {
  fs.writeFileSync(file, buildSummary(results));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const R = JSON.parse(fs.readFileSync(path.join(root, 'out', 'results.json'), 'utf8'));
  writeSummary(R, path.join(root, 'out', 'summary.md'));
  console.log('wrote out/summary.md');
}
