/** The gallery's sample text, in the language of each direction. A dev page: not app strings. */
export const copy = {
  rtl: {
    lang: 'he',
    tokens: 'צבעים, טיפוגרפיה ועומק',
    type: ['כותרת פאנל 20', 'כותרת 16', 'גוף מודגש 14', 'גוף 13 — ברירת המחדל', 'משני 12'],
    buttons: 'כפתורים',
    states: ['רגיל', 'ריחוף', 'לחוץ', 'מיקוד', 'מושבת', 'טעינה'],
    variants: ['ראשי', 'משני', 'שקוף', 'AI', 'מסוכן'],
    buttonLabel: 'שמירה',
    iconButtons: 'כפתורי אייקון ומתגים',
    undo: 'ביטול פעולה',
    bold: 'מודגש',
    italic: 'נטוי',
    underline: 'קו תחתי',
    segmented: 'בורר מקטעים',
    segments: ['שקף', 'מצגת', 'אובייקט'],
    align: ['יישור לימין', 'מרכוז', 'יישור לשמאל'],
    arrows: ['שמאלה', 'למעלה', 'למטה', 'ימינה'],
    options: 'תיבת סימון ומתג',
    optionStates: ['רגיל', 'ריחוף', 'לחוץ', 'מיקוד', 'מושבת'],
    optionRows: ['תיבה', 'מסומנת', 'מעורבת', 'מתג', 'פועל'],
    optionLabel: 'שורת כותרת',
    asDefault: 'לקבוע כברירת מחדל',
    asDefaultHint: 'מצגת חדשה תיפתח בתבנית הזאת.',
    tableParts: ['שורת כותרת', 'שורות מתחלפות', 'עמודה ראשונה'],
    animations: 'אנימציות',
    animationsHint: 'בלי אנימציות הקובץ קטן יותר.',
    field: 'שדה: תווית מעל פקד',
    direction: 'כיוון',
    directionHint: 'מאיפה האובייקט נכנס.',
    duration: 'משך',
    durationError: 'עד 60 שניות.',
    secondsUnit: 'שנ׳',
    send: 'שליחה',
    mono: 'גופן ברוחב קבוע',
    tabs: 'לשוניות',
    tabNames: ["צ'אט", 'פעולות', 'היסטוריה'],
    fields: 'שדות טקסט',
    fieldLabel: 'שם המצגת',
    fieldPlaceholder: 'למשל: סקירה רבעונית',
    fieldHint: 'יופיע בשורת הכותרת.',
    fieldError: 'השם ארוך מדי.',
    search: 'חיפוש',
    menus: 'תפריטים',
    menu: {
      new: 'מצגת חדשה',
      open: 'פתיחה…',
      recent: 'קבצים אחרונים',
      grid: 'הצגת רשת',
      guides: 'קווי עזר',
      fit: 'התאמה לחלון',
      actual: '100%',
      delete: 'מחיקה',
      disabled: 'ייצוא PDF',
      label: 'תצוגה',
      contextHint: 'קליק ימני כאן',
    },
    overlays: 'חלונית ו-tooltip',
    popoverTitle: 'קישור',
    popoverField: 'כתובת',
    apply: 'החלה',
    cancel: 'ביטול',
    dialog: 'דיאלוג',
    dialogTitle: 'לשמור את השינויים ב"סקירה רבעונית"?',
    dialogBody: 'אם לא תשמרו, השינויים יאבדו.',
    dontSave: 'בלי לשמור',
    close: 'סגירה',
    feedback: 'משוב: מקשים, טעינה, ריק ושגיאה',
    emptyTitle: 'אין עדיין תמונות',
    emptyBody: 'גררו לכאן קבצים, או חפשו תמונות סטוק.',
    emptyAction: 'העלאת תמונה',
    errorTitle: 'הטעינה נכשלה',
    errorBody: 'אין חיבור לשירות. נסו שוב בעוד רגע.',
    retry: 'ניסיון חוזר',
    scroll: 'אזור גלילה',
    slide: 'שקף',
    values: 'מספרים, בחירה ומחוון',
    size: 'גודל גופן',
    rotation: 'סיבוב',
    opacity: 'שקיפות',
    weight: 'משקל',
    weights: ['דק', 'רגיל', 'בינוני', 'מודגש'],
    mixed: 'מעורב',
    colorPicker: 'בורר צבע',
    themeColors: 'צבעי התבנית',
    themeNames: ['רקע', 'משטח', 'טקסט', 'משני', 'ראשי', 'שני', 'הדגשה'],
    color: {
      area: 'רוויה ובהירות',
      hue: 'גוון',
      alpha: 'אטימות',
      hex: 'קוד צבע',
      eyedropper: 'טפטפת',
      none: 'ללא צבע',
      recent: 'אחרונים',
    },
    fontPicker: 'בורר גופן',
    font: {
      search: 'חיפוש גופן',
      recent: 'אחרונים',
      all: 'כל הגופנים',
      hebrew: 'תומך בעברית',
      empty: 'לא נמצא גופן כזה',
    },
  },
  ltr: {
    lang: 'en',
    tokens: 'Colour, type and depth',
    type: [
      'Panel title 20',
      'Heading 16',
      'Strong body 14',
      'Body 13 — the default',
      'Secondary 12',
    ],
    buttons: 'Buttons',
    states: ['Rest', 'Hover', 'Pressed', 'Focus', 'Disabled', 'Loading'],
    variants: ['Primary', 'Secondary', 'Ghost', 'AI', 'Danger'],
    buttonLabel: 'Save',
    iconButtons: 'Icon buttons and toggles',
    undo: 'Undo',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    segmented: 'Segmented control',
    segments: ['Slide', 'Deck', 'Object'],
    align: ['Align left', 'Center', 'Align right'],
    arrows: ['Left', 'Up', 'Down', 'Right'],
    options: 'Checkbox and switch',
    optionStates: ['Rest', 'Hover', 'Pressed', 'Focus', 'Disabled'],
    optionRows: ['Box', 'Checked', 'Mixed', 'Switch', 'On'],
    optionLabel: 'Header row',
    asDefault: 'Set as default',
    asDefaultHint: 'New presentations will open with this template.',
    tableParts: ['Header row', 'Banded rows', 'First column'],
    animations: 'Animations',
    animationsHint: 'The file is smaller without animations.',
    field: 'Field: a label over a control',
    direction: 'Direction',
    directionHint: 'Where the object comes in from.',
    duration: 'Duration',
    durationError: 'Up to 60 seconds.',
    secondsUnit: 's',
    send: 'Send',
    mono: 'Fixed-width font',
    tabs: 'Tabs',
    tabNames: ['Chat', 'Actions', 'History'],
    fields: 'Text fields',
    fieldLabel: 'Presentation name',
    fieldPlaceholder: 'e.g. Quarterly review',
    fieldHint: 'Shown in the title bar.',
    fieldError: 'The name is too long.',
    search: 'Search',
    menus: 'Menus',
    menu: {
      new: 'New presentation',
      open: 'Open…',
      recent: 'Open recent',
      grid: 'Show grid',
      guides: 'Guides',
      fit: 'Fit to window',
      actual: '100%',
      delete: 'Delete',
      disabled: 'Export PDF',
      label: 'View',
      contextHint: 'Right-click here',
    },
    overlays: 'Popover and tooltip',
    popoverTitle: 'Link',
    popoverField: 'Address',
    apply: 'Apply',
    cancel: 'Cancel',
    dialog: 'Dialog',
    dialogTitle: 'Save changes to “Quarterly review”?',
    dialogBody: 'Your changes will be lost if you don’t save them.',
    dontSave: 'Don’t save',
    close: 'Close',
    feedback: 'Feedback: keys, loading, empty and error',
    emptyTitle: 'No images yet',
    emptyBody: 'Drop files here, or search stock photos.',
    emptyAction: 'Upload image',
    errorTitle: 'Couldn’t load',
    errorBody: 'The service can’t be reached. Try again in a moment.',
    retry: 'Try again',
    scroll: 'Scroll area',
    slide: 'Slide',
    values: 'Numbers, select and slider',
    size: 'Font size',
    rotation: 'Rotation',
    opacity: 'Opacity',
    weight: 'Weight',
    weights: ['Light', 'Regular', 'Medium', 'Bold'],
    mixed: 'Mixed',
    colorPicker: 'Colour picker',
    themeColors: 'Theme colours',
    themeNames: ['Background', 'Surface', 'Text', 'Muted', 'Primary', 'Secondary', 'Accent'],
    color: {
      area: 'Saturation and brightness',
      hue: 'Hue',
      alpha: 'Opacity',
      hex: 'Hex code',
      eyedropper: 'Eyedropper',
      none: 'No colour',
      recent: 'Recent',
    },
    fontPicker: 'Font picker',
    font: {
      search: 'Search fonts',
      recent: 'Recent',
      all: 'All fonts',
      hebrew: 'Supports Hebrew',
      empty: 'No font by that name',
    },
  },
} as const;

export type Copy = (typeof copy)['rtl'] | (typeof copy)['ltr'];
