/** The gallery's sample text, in the language of each direction. A dev page: not app strings. */
export const copy = {
  rtl: {
    lang: 'he',
    tokens: 'צבעים, טיפוגרפיה ועומק',
    type: ['כותרת פאנל 20', 'כותרת 16', 'גוף מודגש 14', 'גוף 13 — ברירת המחדל', 'משני 12'],
    buttons: 'כפתורים',
    states: ['רגיל', 'ריחוף', 'לחוץ', 'מיקוד', 'מושבת', 'טעינה'],
    variants: ['ראשי', 'משני', 'שקוף', 'AI', 'מסוכן'],
    buttonLabel: 'שמירה',
    iconButtons: 'כפתורי אייקון ומתגים',
    undo: 'ביטול פעולה',
    bold: 'מודגש',
    italic: 'נטוי',
    underline: 'קו תחתי',
    segmented: 'בורר מקטעים',
    segments: ['שקף', 'מצגת', 'אובייקט'],
    align: ['יישור לימין', 'מרכוז', 'יישור לשמאל'],
    tabs: 'לשוניות',
    tabNames: ["צ'אט", 'פעולות', 'היסטוריה'],
    fields: 'שדות טקסט',
    fieldLabel: 'שם המצגת',
    fieldPlaceholder: 'למשל: סקירה רבעונית',
    fieldHint: 'יופיע בשורת הכותרת.',
    fieldError: 'השם ארוך מדי.',
    search: 'חיפוש',
    menus: 'תפריטים',
    menu: {
      new: 'מצגת חדשה',
      open: 'פתיחה…',
      recent: 'קבצים אחרונים',
      grid: 'הצגת רשת',
      guides: 'קווי עזר',
      fit: 'התאמה לחלון',
      actual: '100%',
      delete: 'מחיקה',
      disabled: 'ייצוא PDF',
      label: 'תצוגה',
      contextHint: 'קליק ימני כאן',
    },
    overlays: 'חלונית ו-tooltip',
    popoverTitle: 'קישור',
    popoverField: 'כתובת',
    apply: 'החלה',
    cancel: 'ביטול',
    dialog: 'דיאלוג',
    dialogTitle: 'לשמור את השינויים ב"סקירה רבעונית"?',
    dialogBody: 'אם לא תשמרו, השינויים יאבדו.',
    dontSave: 'בלי לשמור',
    close: 'סגירה',
    feedback: 'משוב: מקשים, טעינה, ריק ושגיאה',
    emptyTitle: 'אין עדיין תמונות',
    emptyBody: 'גררו לכאן קבצים, או חפשו תמונות סטוק.',
    emptyAction: 'העלאת תמונה',
    errorTitle: 'הטעינה נכשלה',
    errorBody: 'אין חיבור לשירות. נסו שוב בעוד רגע.',
    retry: 'ניסיון חוזר',
    scroll: 'אזור גלילה',
    slide: 'שקף',
  },
  ltr: {
    lang: 'en',
    tokens: 'Colour, type and depth',
    type: [
      'Panel title 20',
      'Heading 16',
      'Strong body 14',
      'Body 13 — the default',
      'Secondary 12',
    ],
    buttons: 'Buttons',
    states: ['Rest', 'Hover', 'Pressed', 'Focus', 'Disabled', 'Loading'],
    variants: ['Primary', 'Secondary', 'Ghost', 'AI', 'Danger'],
    buttonLabel: 'Save',
    iconButtons: 'Icon buttons and toggles',
    undo: 'Undo',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    segmented: 'Segmented control',
    segments: ['Slide', 'Deck', 'Object'],
    align: ['Align left', 'Center', 'Align right'],
    tabs: 'Tabs',
    tabNames: ['Chat', 'Actions', 'History'],
    fields: 'Text fields',
    fieldLabel: 'Presentation name',
    fieldPlaceholder: 'e.g. Quarterly review',
    fieldHint: 'Shown in the title bar.',
    fieldError: 'The name is too long.',
    search: 'Search',
    menus: 'Menus',
    menu: {
      new: 'New presentation',
      open: 'Open…',
      recent: 'Open recent',
      grid: 'Show grid',
      guides: 'Guides',
      fit: 'Fit to window',
      actual: '100%',
      delete: 'Delete',
      disabled: 'Export PDF',
      label: 'View',
      contextHint: 'Right-click here',
    },
    overlays: 'Popover and tooltip',
    popoverTitle: 'Link',
    popoverField: 'Address',
    apply: 'Apply',
    cancel: 'Cancel',
    dialog: 'Dialog',
    dialogTitle: 'Save changes to “Quarterly review”?',
    dialogBody: 'Your changes will be lost if you don’t save them.',
    dontSave: 'Don’t save',
    close: 'Close',
    feedback: 'Feedback: keys, loading, empty and error',
    emptyTitle: 'No images yet',
    emptyBody: 'Drop files here, or search stock photos.',
    emptyAction: 'Upload image',
    errorTitle: 'Couldn’t load',
    errorBody: 'The service can’t be reached. Try again in a moment.',
    retry: 'Try again',
    scroll: 'Scroll area',
    slide: 'Slide',
  },
} as const;

export type Copy = (typeof copy)['rtl'] | (typeof copy)['ltr'];
