// Generated by scripts/gen-builtin-fonts.mjs. Do not edit.
import f0 from '@fontsource-variable/heebo/files/heebo-hebrew-wght-normal.woff2?url';
import f1 from '@fontsource-variable/heebo/files/heebo-math-wght-normal.woff2?url';
import f2 from '@fontsource-variable/heebo/files/heebo-symbols-wght-normal.woff2?url';
import f3 from '@fontsource-variable/heebo/files/heebo-latin-ext-wght-normal.woff2?url';
import f4 from '@fontsource-variable/heebo/files/heebo-latin-wght-normal.woff2?url';
import f5 from '@fontsource-variable/rubik/files/rubik-hebrew-wght-normal.woff2?url';
import f6 from '@fontsource-variable/rubik/files/rubik-latin-ext-wght-normal.woff2?url';
import f7 from '@fontsource-variable/rubik/files/rubik-latin-wght-normal.woff2?url';
import f8 from '@fontsource-variable/rubik/files/rubik-hebrew-wght-italic.woff2?url';
import f9 from '@fontsource-variable/rubik/files/rubik-latin-ext-wght-italic.woff2?url';
import f10 from '@fontsource-variable/rubik/files/rubik-latin-wght-italic.woff2?url';
import f11 from '@fontsource-variable/assistant/files/assistant-hebrew-wght-normal.woff2?url';
import f12 from '@fontsource-variable/assistant/files/assistant-latin-ext-wght-normal.woff2?url';
import f13 from '@fontsource-variable/assistant/files/assistant-latin-wght-normal.woff2?url';
import f14 from '@fontsource-variable/noto-sans-hebrew/files/noto-sans-hebrew-cyrillic-ext-wght-normal.woff2?url';
import f15 from '@fontsource-variable/noto-sans-hebrew/files/noto-sans-hebrew-greek-ext-wght-normal.woff2?url';
import f16 from '@fontsource-variable/noto-sans-hebrew/files/noto-sans-hebrew-hebrew-wght-normal.woff2?url';
import f17 from '@fontsource-variable/noto-sans-hebrew/files/noto-sans-hebrew-latin-ext-wght-normal.woff2?url';
import f18 from '@fontsource-variable/noto-sans-hebrew/files/noto-sans-hebrew-latin-wght-normal.woff2?url';
import f19 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-100-normal.woff2?url';
import f20 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-100-normal.woff2?url';
import f21 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-100-normal.woff2?url';
import f22 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-100-normal.woff2?url';
import f23 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-200-normal.woff2?url';
import f24 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-200-normal.woff2?url';
import f25 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-200-normal.woff2?url';
import f26 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-200-normal.woff2?url';
import f27 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-300-normal.woff2?url';
import f28 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-300-normal.woff2?url';
import f29 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-300-normal.woff2?url';
import f30 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-300-normal.woff2?url';
import f31 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-400-normal.woff2?url';
import f32 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-400-normal.woff2?url';
import f33 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-400-normal.woff2?url';
import f34 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-400-normal.woff2?url';
import f35 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-500-normal.woff2?url';
import f36 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-500-normal.woff2?url';
import f37 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-500-normal.woff2?url';
import f38 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-500-normal.woff2?url';
import f39 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-600-normal.woff2?url';
import f40 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-600-normal.woff2?url';
import f41 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-600-normal.woff2?url';
import f42 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-600-normal.woff2?url';
import f43 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-cyrillic-ext-700-normal.woff2?url';
import f44 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-hebrew-700-normal.woff2?url';
import f45 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-ext-700-normal.woff2?url';
import f46 from '@fontsource/ibm-plex-sans-hebrew/files/ibm-plex-sans-hebrew-latin-700-normal.woff2?url';
import f47 from '@fontsource-variable/open-sans/files/open-sans-hebrew-wght-normal.woff2?url';
import f48 from '@fontsource-variable/open-sans/files/open-sans-math-wght-normal.woff2?url';
import f49 from '@fontsource-variable/open-sans/files/open-sans-symbols-wght-normal.woff2?url';
import f50 from '@fontsource-variable/open-sans/files/open-sans-latin-ext-wght-normal.woff2?url';
import f51 from '@fontsource-variable/open-sans/files/open-sans-latin-wght-normal.woff2?url';
import f52 from '@fontsource-variable/open-sans/files/open-sans-hebrew-wght-italic.woff2?url';
import f53 from '@fontsource-variable/open-sans/files/open-sans-math-wght-italic.woff2?url';
import f54 from '@fontsource-variable/open-sans/files/open-sans-symbols-wght-italic.woff2?url';
import f55 from '@fontsource-variable/open-sans/files/open-sans-latin-ext-wght-italic.woff2?url';
import f56 from '@fontsource-variable/open-sans/files/open-sans-latin-wght-italic.woff2?url';
import f57 from '@fontsource/alef/files/alef-hebrew-400-normal.woff2?url';
import f58 from '@fontsource/alef/files/alef-latin-400-normal.woff2?url';
import f59 from '@fontsource/alef/files/alef-hebrew-700-normal.woff2?url';
import f60 from '@fontsource/alef/files/alef-latin-700-normal.woff2?url';
import f61 from '@fontsource/varela-round/files/varela-round-hebrew-400-normal.woff2?url';
import f62 from '@fontsource/varela-round/files/varela-round-latin-ext-400-normal.woff2?url';
import f63 from '@fontsource/varela-round/files/varela-round-latin-400-normal.woff2?url';
import f64 from '@fontsource-variable/frank-ruhl-libre/files/frank-ruhl-libre-hebrew-wght-normal.woff2?url';
import f65 from '@fontsource-variable/frank-ruhl-libre/files/frank-ruhl-libre-latin-ext-wght-normal.woff2?url';
import f66 from '@fontsource-variable/frank-ruhl-libre/files/frank-ruhl-libre-latin-wght-normal.woff2?url';
import f67 from '@fontsource/david-libre/files/david-libre-hebrew-400-normal.woff2?url';
import f68 from '@fontsource/david-libre/files/david-libre-math-400-normal.woff2?url';
import f69 from '@fontsource/david-libre/files/david-libre-symbols-400-normal.woff2?url';
import f70 from '@fontsource/david-libre/files/david-libre-latin-ext-400-normal.woff2?url';
import f71 from '@fontsource/david-libre/files/david-libre-latin-400-normal.woff2?url';
import f72 from '@fontsource/david-libre/files/david-libre-hebrew-500-normal.woff2?url';
import f73 from '@fontsource/david-libre/files/david-libre-math-500-normal.woff2?url';
import f74 from '@fontsource/david-libre/files/david-libre-symbols-500-normal.woff2?url';
import f75 from '@fontsource/david-libre/files/david-libre-latin-ext-500-normal.woff2?url';
import f76 from '@fontsource/david-libre/files/david-libre-latin-500-normal.woff2?url';
import f77 from '@fontsource/david-libre/files/david-libre-hebrew-700-normal.woff2?url';
import f78 from '@fontsource/david-libre/files/david-libre-math-700-normal.woff2?url';
import f79 from '@fontsource/david-libre/files/david-libre-symbols-700-normal.woff2?url';
import f80 from '@fontsource/david-libre/files/david-libre-latin-ext-700-normal.woff2?url';
import f81 from '@fontsource/david-libre/files/david-libre-latin-700-normal.woff2?url';
import f82 from '@fontsource-variable/noto-serif-hebrew/files/noto-serif-hebrew-hebrew-wght-normal.woff2?url';
import f83 from '@fontsource-variable/noto-serif-hebrew/files/noto-serif-hebrew-latin-ext-wght-normal.woff2?url';
import f84 from '@fontsource-variable/noto-serif-hebrew/files/noto-serif-hebrew-latin-wght-normal.woff2?url';
import f85 from '@fontsource/secular-one/files/secular-one-hebrew-400-normal.woff2?url';
import f86 from '@fontsource/secular-one/files/secular-one-latin-ext-400-normal.woff2?url';
import f87 from '@fontsource/secular-one/files/secular-one-latin-400-normal.woff2?url';
import f88 from '@fontsource/suez-one/files/suez-one-hebrew-400-normal.woff2?url';
import f89 from '@fontsource/suez-one/files/suez-one-latin-ext-400-normal.woff2?url';
import f90 from '@fontsource/suez-one/files/suez-one-latin-400-normal.woff2?url';
import f91 from '@fontsource/karantina/files/karantina-hebrew-300-normal.woff2?url';
import f92 from '@fontsource/karantina/files/karantina-latin-ext-300-normal.woff2?url';
import f93 from '@fontsource/karantina/files/karantina-latin-300-normal.woff2?url';
import f94 from '@fontsource/karantina/files/karantina-hebrew-400-normal.woff2?url';
import f95 from '@fontsource/karantina/files/karantina-latin-ext-400-normal.woff2?url';
import f96 from '@fontsource/karantina/files/karantina-latin-400-normal.woff2?url';
import f97 from '@fontsource/karantina/files/karantina-hebrew-700-normal.woff2?url';
import f98 from '@fontsource/karantina/files/karantina-latin-ext-700-normal.woff2?url';
import f99 from '@fontsource/karantina/files/karantina-latin-700-normal.woff2?url';
import f100 from '@fontsource-variable/inter/files/inter-latin-ext-wght-normal.woff2?url';
import f101 from '@fontsource-variable/inter/files/inter-latin-wght-normal.woff2?url';
import f102 from '@fontsource-variable/inter/files/inter-latin-ext-wght-italic.woff2?url';
import f103 from '@fontsource-variable/inter/files/inter-latin-wght-italic.woff2?url';
import f104 from '@fontsource/poppins/files/poppins-latin-ext-100-italic.woff2?url';
import f105 from '@fontsource/poppins/files/poppins-latin-100-italic.woff2?url';
import f106 from '@fontsource/poppins/files/poppins-latin-ext-100-normal.woff2?url';
import f107 from '@fontsource/poppins/files/poppins-latin-100-normal.woff2?url';
import f108 from '@fontsource/poppins/files/poppins-latin-ext-200-italic.woff2?url';
import f109 from '@fontsource/poppins/files/poppins-latin-200-italic.woff2?url';
import f110 from '@fontsource/poppins/files/poppins-latin-ext-200-normal.woff2?url';
import f111 from '@fontsource/poppins/files/poppins-latin-200-normal.woff2?url';
import f112 from '@fontsource/poppins/files/poppins-latin-ext-300-italic.woff2?url';
import f113 from '@fontsource/poppins/files/poppins-latin-300-italic.woff2?url';
import f114 from '@fontsource/poppins/files/poppins-latin-ext-300-normal.woff2?url';
import f115 from '@fontsource/poppins/files/poppins-latin-300-normal.woff2?url';
import f116 from '@fontsource/poppins/files/poppins-latin-ext-400-italic.woff2?url';
import f117 from '@fontsource/poppins/files/poppins-latin-400-italic.woff2?url';
import f118 from '@fontsource/poppins/files/poppins-latin-ext-400-normal.woff2?url';
import f119 from '@fontsource/poppins/files/poppins-latin-400-normal.woff2?url';
import f120 from '@fontsource/poppins/files/poppins-latin-ext-500-italic.woff2?url';
import f121 from '@fontsource/poppins/files/poppins-latin-500-italic.woff2?url';
import f122 from '@fontsource/poppins/files/poppins-latin-ext-500-normal.woff2?url';
import f123 from '@fontsource/poppins/files/poppins-latin-500-normal.woff2?url';
import f124 from '@fontsource/poppins/files/poppins-latin-ext-600-italic.woff2?url';
import f125 from '@fontsource/poppins/files/poppins-latin-600-italic.woff2?url';
import f126 from '@fontsource/poppins/files/poppins-latin-ext-600-normal.woff2?url';
import f127 from '@fontsource/poppins/files/poppins-latin-600-normal.woff2?url';
import f128 from '@fontsource/poppins/files/poppins-latin-ext-700-italic.woff2?url';
import f129 from '@fontsource/poppins/files/poppins-latin-700-italic.woff2?url';
import f130 from '@fontsource/poppins/files/poppins-latin-ext-700-normal.woff2?url';
import f131 from '@fontsource/poppins/files/poppins-latin-700-normal.woff2?url';
import f132 from '@fontsource/poppins/files/poppins-latin-ext-800-italic.woff2?url';
import f133 from '@fontsource/poppins/files/poppins-latin-800-italic.woff2?url';
import f134 from '@fontsource/poppins/files/poppins-latin-ext-800-normal.woff2?url';
import f135 from '@fontsource/poppins/files/poppins-latin-800-normal.woff2?url';
import f136 from '@fontsource/poppins/files/poppins-latin-ext-900-italic.woff2?url';
import f137 from '@fontsource/poppins/files/poppins-latin-900-italic.woff2?url';
import f138 from '@fontsource/poppins/files/poppins-latin-ext-900-normal.woff2?url';
import f139 from '@fontsource/poppins/files/poppins-latin-900-normal.woff2?url';
import f140 from '@fontsource-variable/montserrat/files/montserrat-latin-ext-wght-normal.woff2?url';
import f141 from '@fontsource-variable/montserrat/files/montserrat-latin-wght-normal.woff2?url';
import f142 from '@fontsource-variable/montserrat/files/montserrat-latin-ext-wght-italic.woff2?url';
import f143 from '@fontsource-variable/montserrat/files/montserrat-latin-wght-italic.woff2?url';
import f144 from '@fontsource-variable/manrope/files/manrope-latin-ext-wght-normal.woff2?url';
import f145 from '@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2?url';
import f146 from '@fontsource-variable/dm-sans/files/dm-sans-latin-ext-wght-normal.woff2?url';
import f147 from '@fontsource-variable/dm-sans/files/dm-sans-latin-wght-normal.woff2?url';
import f148 from '@fontsource-variable/dm-sans/files/dm-sans-latin-ext-wght-italic.woff2?url';
import f149 from '@fontsource-variable/dm-sans/files/dm-sans-latin-wght-italic.woff2?url';
import f150 from '@fontsource-variable/space-grotesk/files/space-grotesk-latin-ext-wght-normal.woff2?url';
import f151 from '@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2?url';
import f152 from '@fontsource-variable/playfair-display/files/playfair-display-latin-ext-wght-normal.woff2?url';
import f153 from '@fontsource-variable/playfair-display/files/playfair-display-latin-wght-normal.woff2?url';
import f154 from '@fontsource-variable/playfair-display/files/playfair-display-latin-ext-wght-italic.woff2?url';
import f155 from '@fontsource-variable/playfair-display/files/playfair-display-latin-wght-italic.woff2?url';
import f156 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-ext-400-italic.woff2?url';
import f157 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-400-italic.woff2?url';
import f158 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-ext-400-normal.woff2?url';
import f159 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff2?url';
import f160 from '@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-ext-wght-normal.woff2?url';
import f161 from '@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2?url';
import f162 from '@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-ext-wght-italic.woff2?url';
import f163 from '@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-italic.woff2?url';

export interface BuiltinFace {
  family: string;
  style: string;
  weight: string;
  url: string;
  unicodeRange?: string;
}

export const builtinFamilies = [
  {
    family: 'Heebo',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Rubik',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Assistant',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Noto Sans Hebrew',
    scripts: ['he', 'latin'],
  },
  {
    family: 'IBM Plex Sans Hebrew',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Open Sans',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Alef',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Varela Round',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Frank Ruhl Libre',
    scripts: ['he', 'latin'],
  },
  {
    family: 'David Libre',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Noto Serif Hebrew',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Secular One',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Suez One',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Karantina',
    scripts: ['he', 'latin'],
  },
  {
    family: 'Inter',
    scripts: ['latin'],
  },
  {
    family: 'Poppins',
    scripts: ['latin'],
  },
  {
    family: 'Montserrat',
    scripts: ['latin'],
  },
  {
    family: 'Manrope',
    scripts: ['latin'],
  },
  {
    family: 'DM Sans',
    scripts: ['latin'],
  },
  {
    family: 'Space Grotesk',
    scripts: ['latin'],
  },
  {
    family: 'Playfair Display',
    scripts: ['latin'],
  },
  {
    family: 'DM Serif Display',
    scripts: ['latin'],
  },
  {
    family: 'JetBrains Mono',
    scripts: ['latin'],
  },
] as const;

export const builtinFaces: BuiltinFace[] = [
  {
    family: 'Heebo',
    style: 'normal',
    weight: '100 900',
    url: f0,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Heebo',
    style: 'normal',
    weight: '100 900',
    url: f1,
    unicodeRange:
      'U+0302-0303,U+0305,U+0307-0308,U+0310,U+0312,U+0315,U+031A,U+0326-0327,U+032C,U+032F-0330,U+0332-0333,U+0338,U+033A,U+0346,U+034D,U+0391-03A1,U+03A3-03A9,U+03B1-03C9,U+03D1,U+03D5-03D6,U+03F0-03F1,U+03F4-03F5,U+2016-2017,U+2034-2038,U+203C,U+2040,U+2043,U+2047,U+2050,U+2057,U+205F,U+2070-2071,U+2074-208E,U+2090-209C,U+20D0-20DC,U+20E1,U+20E5-20EF,U+2100-2112,U+2114-2115,U+2117-2121,U+2123-214F,U+2190,U+2192,U+2194-21AE,U+21B0-21E5,U+21F1-21F2,U+21F4-2211,U+2213-2214,U+2216-22FF,U+2308-230B,U+2310,U+2319,U+231C-2321,U+2336-237A,U+237C,U+2395,U+239B-23B7,U+23D0,U+23DC-23E1,U+2474-2475,U+25AF,U+25B3,U+25B7,U+25BD,U+25C1,U+25CA,U+25CC,U+25FB,U+266D-266F,U+27C0-27FF,U+2900-2AFF,U+2B0E-2B11,U+2B30-2B4C,U+2BFE,U+3030,U+FF5B,U+FF5D,U+1D400-1D7FF,U+1EE00-1EEFF',
  },
  {
    family: 'Heebo',
    style: 'normal',
    weight: '100 900',
    url: f2,
    unicodeRange:
      'U+0001-000C,U+000E-001F,U+007F-009F,U+20DD-20E0,U+20E2-20E4,U+2150-218F,U+2190,U+2192,U+2194-2199,U+21AF,U+21E6-21F0,U+21F3,U+2218-2219,U+2299,U+22C4-22C6,U+2300-243F,U+2440-244A,U+2460-24FF,U+25A0-27BF,U+2800-28FF,U+2921-2922,U+2981,U+29BF,U+29EB,U+2B00-2BFF,U+4DC0-4DFF,U+FFF9-FFFB,U+10140-1018E,U+10190-1019C,U+101A0,U+101D0-101FD,U+102E0-102FB,U+10E60-10E7E,U+1D2C0-1D2D3,U+1D2E0-1D37F,U+1F000-1F0FF,U+1F100-1F1AD,U+1F1E6-1F1FF,U+1F30D-1F30F,U+1F315,U+1F31C,U+1F31E,U+1F320-1F32C,U+1F336,U+1F378,U+1F37D,U+1F382,U+1F393-1F39F,U+1F3A7-1F3A8,U+1F3AC-1F3AF,U+1F3C2,U+1F3C4-1F3C6,U+1F3CA-1F3CE,U+1F3D4-1F3E0,U+1F3ED,U+1F3F1-1F3F3,U+1F3F5-1F3F7,U+1F408,U+1F415,U+1F41F,U+1F426,U+1F43F,U+1F441-1F442,U+1F444,U+1F446-1F449,U+1F44C-1F44E,U+1F453,U+1F46A,U+1F47D,U+1F4A3,U+1F4B0,U+1F4B3,U+1F4B9,U+1F4BB,U+1F4BF,U+1F4C8-1F4CB,U+1F4D6,U+1F4DA,U+1F4DF,U+1F4E3-1F4E6,U+1F4EA-1F4ED,U+1F4F7,U+1F4F9-1F4FB,U+1F4FD-1F4FE,U+1F503,U+1F507-1F50B,U+1F50D,U+1F512-1F513,U+1F53E-1F54A,U+1F54F-1F5FA,U+1F610,U+1F650-1F67F,U+1F687,U+1F68D,U+1F691,U+1F694,U+1F698,U+1F6AD,U+1F6B2,U+1F6B9-1F6BA,U+1F6BC,U+1F6C6-1F6CF,U+1F6D3-1F6D7,U+1F6E0-1F6EA,U+1F6F0-1F6F3,U+1F6F7-1F6FC,U+1F700-1F7FF,U+1F800-1F80B,U+1F810-1F847,U+1F850-1F859,U+1F860-1F887,U+1F890-1F8AD,U+1F8B0-1F8BB,U+1F8C0-1F8C1,U+1F900-1F90B,U+1F93B,U+1F946,U+1F984,U+1F996,U+1F9E9,U+1FA00-1FA6F,U+1FA70-1FA7C,U+1FA80-1FA89,U+1FA8F-1FAC6,U+1FACE-1FADC,U+1FADF-1FAE9,U+1FAF0-1FAF8,U+1FB00-1FBFF',
  },
  {
    family: 'Heebo',
    style: 'normal',
    weight: '100 900',
    url: f3,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Heebo',
    style: 'normal',
    weight: '100 900',
    url: f4,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Rubik',
    style: 'normal',
    weight: '300 900',
    url: f5,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Rubik',
    style: 'normal',
    weight: '300 900',
    url: f6,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Rubik',
    style: 'normal',
    weight: '300 900',
    url: f7,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Rubik',
    style: 'italic',
    weight: '300 900',
    url: f8,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Rubik',
    style: 'italic',
    weight: '300 900',
    url: f9,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Rubik',
    style: 'italic',
    weight: '300 900',
    url: f10,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Assistant',
    style: 'normal',
    weight: '200 800',
    url: f11,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Assistant',
    style: 'normal',
    weight: '200 800',
    url: f12,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Assistant',
    style: 'normal',
    weight: '200 800',
    url: f13,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Noto Sans Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f14,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'Noto Sans Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f15,
    unicodeRange: 'U+1F00-1FFF',
  },
  {
    family: 'Noto Sans Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f16,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Noto Sans Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f17,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Noto Sans Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f18,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '100',
    url: f19,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '100',
    url: f20,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '100',
    url: f21,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '100',
    url: f22,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '200',
    url: f23,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '200',
    url: f24,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '200',
    url: f25,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '200',
    url: f26,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '300',
    url: f27,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '300',
    url: f28,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '300',
    url: f29,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '300',
    url: f30,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '400',
    url: f31,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '400',
    url: f32,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '400',
    url: f33,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '400',
    url: f34,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '500',
    url: f35,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '500',
    url: f36,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '500',
    url: f37,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '500',
    url: f38,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '600',
    url: f39,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '600',
    url: f40,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '600',
    url: f41,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '600',
    url: f42,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '700',
    url: f43,
    unicodeRange: 'U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '700',
    url: f44,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '700',
    url: f45,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'IBM Plex Sans Hebrew',
    style: 'normal',
    weight: '700',
    url: f46,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Open Sans',
    style: 'normal',
    weight: '300 800',
    url: f47,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Open Sans',
    style: 'normal',
    weight: '300 800',
    url: f48,
    unicodeRange:
      'U+0302-0303,U+0305,U+0307-0308,U+0310,U+0312,U+0315,U+031A,U+0326-0327,U+032C,U+032F-0330,U+0332-0333,U+0338,U+033A,U+0346,U+034D,U+0391-03A1,U+03A3-03A9,U+03B1-03C9,U+03D1,U+03D5-03D6,U+03F0-03F1,U+03F4-03F5,U+2016-2017,U+2034-2038,U+203C,U+2040,U+2043,U+2047,U+2050,U+2057,U+205F,U+2070-2071,U+2074-208E,U+2090-209C,U+20D0-20DC,U+20E1,U+20E5-20EF,U+2100-2112,U+2114-2115,U+2117-2121,U+2123-214F,U+2190,U+2192,U+2194-21AE,U+21B0-21E5,U+21F1-21F2,U+21F4-2211,U+2213-2214,U+2216-22FF,U+2308-230B,U+2310,U+2319,U+231C-2321,U+2336-237A,U+237C,U+2395,U+239B-23B7,U+23D0,U+23DC-23E1,U+2474-2475,U+25AF,U+25B3,U+25B7,U+25BD,U+25C1,U+25CA,U+25CC,U+25FB,U+266D-266F,U+27C0-27FF,U+2900-2AFF,U+2B0E-2B11,U+2B30-2B4C,U+2BFE,U+3030,U+FF5B,U+FF5D,U+1D400-1D7FF,U+1EE00-1EEFF',
  },
  {
    family: 'Open Sans',
    style: 'normal',
    weight: '300 800',
    url: f49,
    unicodeRange:
      'U+0001-000C,U+000E-001F,U+007F-009F,U+20DD-20E0,U+20E2-20E4,U+2150-218F,U+2190,U+2192,U+2194-2199,U+21AF,U+21E6-21F0,U+21F3,U+2218-2219,U+2299,U+22C4-22C6,U+2300-243F,U+2440-244A,U+2460-24FF,U+25A0-27BF,U+2800-28FF,U+2921-2922,U+2981,U+29BF,U+29EB,U+2B00-2BFF,U+4DC0-4DFF,U+FFF9-FFFB,U+10140-1018E,U+10190-1019C,U+101A0,U+101D0-101FD,U+102E0-102FB,U+10E60-10E7E,U+1D2C0-1D2D3,U+1D2E0-1D37F,U+1F000-1F0FF,U+1F100-1F1AD,U+1F1E6-1F1FF,U+1F30D-1F30F,U+1F315,U+1F31C,U+1F31E,U+1F320-1F32C,U+1F336,U+1F378,U+1F37D,U+1F382,U+1F393-1F39F,U+1F3A7-1F3A8,U+1F3AC-1F3AF,U+1F3C2,U+1F3C4-1F3C6,U+1F3CA-1F3CE,U+1F3D4-1F3E0,U+1F3ED,U+1F3F1-1F3F3,U+1F3F5-1F3F7,U+1F408,U+1F415,U+1F41F,U+1F426,U+1F43F,U+1F441-1F442,U+1F444,U+1F446-1F449,U+1F44C-1F44E,U+1F453,U+1F46A,U+1F47D,U+1F4A3,U+1F4B0,U+1F4B3,U+1F4B9,U+1F4BB,U+1F4BF,U+1F4C8-1F4CB,U+1F4D6,U+1F4DA,U+1F4DF,U+1F4E3-1F4E6,U+1F4EA-1F4ED,U+1F4F7,U+1F4F9-1F4FB,U+1F4FD-1F4FE,U+1F503,U+1F507-1F50B,U+1F50D,U+1F512-1F513,U+1F53E-1F54A,U+1F54F-1F5FA,U+1F610,U+1F650-1F67F,U+1F687,U+1F68D,U+1F691,U+1F694,U+1F698,U+1F6AD,U+1F6B2,U+1F6B9-1F6BA,U+1F6BC,U+1F6C6-1F6CF,U+1F6D3-1F6D7,U+1F6E0-1F6EA,U+1F6F0-1F6F3,U+1F6F7-1F6FC,U+1F700-1F7FF,U+1F800-1F80B,U+1F810-1F847,U+1F850-1F859,U+1F860-1F887,U+1F890-1F8AD,U+1F8B0-1F8BB,U+1F8C0-1F8C1,U+1F900-1F90B,U+1F93B,U+1F946,U+1F984,U+1F996,U+1F9E9,U+1FA00-1FA6F,U+1FA70-1FA7C,U+1FA80-1FA89,U+1FA8F-1FAC6,U+1FACE-1FADC,U+1FADF-1FAE9,U+1FAF0-1FAF8,U+1FB00-1FBFF',
  },
  {
    family: 'Open Sans',
    style: 'normal',
    weight: '300 800',
    url: f50,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Open Sans',
    style: 'normal',
    weight: '300 800',
    url: f51,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Open Sans',
    style: 'italic',
    weight: '300 800',
    url: f52,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Open Sans',
    style: 'italic',
    weight: '300 800',
    url: f53,
    unicodeRange:
      'U+0302-0303,U+0305,U+0307-0308,U+0310,U+0312,U+0315,U+031A,U+0326-0327,U+032C,U+032F-0330,U+0332-0333,U+0338,U+033A,U+0346,U+034D,U+0391-03A1,U+03A3-03A9,U+03B1-03C9,U+03D1,U+03D5-03D6,U+03F0-03F1,U+03F4-03F5,U+2016-2017,U+2034-2038,U+203C,U+2040,U+2043,U+2047,U+2050,U+2057,U+205F,U+2070-2071,U+2074-208E,U+2090-209C,U+20D0-20DC,U+20E1,U+20E5-20EF,U+2100-2112,U+2114-2115,U+2117-2121,U+2123-214F,U+2190,U+2192,U+2194-21AE,U+21B0-21E5,U+21F1-21F2,U+21F4-2211,U+2213-2214,U+2216-22FF,U+2308-230B,U+2310,U+2319,U+231C-2321,U+2336-237A,U+237C,U+2395,U+239B-23B7,U+23D0,U+23DC-23E1,U+2474-2475,U+25AF,U+25B3,U+25B7,U+25BD,U+25C1,U+25CA,U+25CC,U+25FB,U+266D-266F,U+27C0-27FF,U+2900-2AFF,U+2B0E-2B11,U+2B30-2B4C,U+2BFE,U+3030,U+FF5B,U+FF5D,U+1D400-1D7FF,U+1EE00-1EEFF',
  },
  {
    family: 'Open Sans',
    style: 'italic',
    weight: '300 800',
    url: f54,
    unicodeRange:
      'U+0001-000C,U+000E-001F,U+007F-009F,U+20DD-20E0,U+20E2-20E4,U+2150-218F,U+2190,U+2192,U+2194-2199,U+21AF,U+21E6-21F0,U+21F3,U+2218-2219,U+2299,U+22C4-22C6,U+2300-243F,U+2440-244A,U+2460-24FF,U+25A0-27BF,U+2800-28FF,U+2921-2922,U+2981,U+29BF,U+29EB,U+2B00-2BFF,U+4DC0-4DFF,U+FFF9-FFFB,U+10140-1018E,U+10190-1019C,U+101A0,U+101D0-101FD,U+102E0-102FB,U+10E60-10E7E,U+1D2C0-1D2D3,U+1D2E0-1D37F,U+1F000-1F0FF,U+1F100-1F1AD,U+1F1E6-1F1FF,U+1F30D-1F30F,U+1F315,U+1F31C,U+1F31E,U+1F320-1F32C,U+1F336,U+1F378,U+1F37D,U+1F382,U+1F393-1F39F,U+1F3A7-1F3A8,U+1F3AC-1F3AF,U+1F3C2,U+1F3C4-1F3C6,U+1F3CA-1F3CE,U+1F3D4-1F3E0,U+1F3ED,U+1F3F1-1F3F3,U+1F3F5-1F3F7,U+1F408,U+1F415,U+1F41F,U+1F426,U+1F43F,U+1F441-1F442,U+1F444,U+1F446-1F449,U+1F44C-1F44E,U+1F453,U+1F46A,U+1F47D,U+1F4A3,U+1F4B0,U+1F4B3,U+1F4B9,U+1F4BB,U+1F4BF,U+1F4C8-1F4CB,U+1F4D6,U+1F4DA,U+1F4DF,U+1F4E3-1F4E6,U+1F4EA-1F4ED,U+1F4F7,U+1F4F9-1F4FB,U+1F4FD-1F4FE,U+1F503,U+1F507-1F50B,U+1F50D,U+1F512-1F513,U+1F53E-1F54A,U+1F54F-1F5FA,U+1F610,U+1F650-1F67F,U+1F687,U+1F68D,U+1F691,U+1F694,U+1F698,U+1F6AD,U+1F6B2,U+1F6B9-1F6BA,U+1F6BC,U+1F6C6-1F6CF,U+1F6D3-1F6D7,U+1F6E0-1F6EA,U+1F6F0-1F6F3,U+1F6F7-1F6FC,U+1F700-1F7FF,U+1F800-1F80B,U+1F810-1F847,U+1F850-1F859,U+1F860-1F887,U+1F890-1F8AD,U+1F8B0-1F8BB,U+1F8C0-1F8C1,U+1F900-1F90B,U+1F93B,U+1F946,U+1F984,U+1F996,U+1F9E9,U+1FA00-1FA6F,U+1FA70-1FA7C,U+1FA80-1FA89,U+1FA8F-1FAC6,U+1FACE-1FADC,U+1FADF-1FAE9,U+1FAF0-1FAF8,U+1FB00-1FBFF',
  },
  {
    family: 'Open Sans',
    style: 'italic',
    weight: '300 800',
    url: f55,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Open Sans',
    style: 'italic',
    weight: '300 800',
    url: f56,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Alef',
    style: 'normal',
    weight: '400',
    url: f57,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Alef',
    style: 'normal',
    weight: '400',
    url: f58,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Alef',
    style: 'normal',
    weight: '700',
    url: f59,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Alef',
    style: 'normal',
    weight: '700',
    url: f60,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Varela Round',
    style: 'normal',
    weight: '400',
    url: f61,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Varela Round',
    style: 'normal',
    weight: '400',
    url: f62,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Varela Round',
    style: 'normal',
    weight: '400',
    url: f63,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Frank Ruhl Libre',
    style: 'normal',
    weight: '300 900',
    url: f64,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Frank Ruhl Libre',
    style: 'normal',
    weight: '300 900',
    url: f65,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Frank Ruhl Libre',
    style: 'normal',
    weight: '300 900',
    url: f66,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '400',
    url: f67,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '400',
    url: f68,
    unicodeRange:
      'U+0302-0303,U+0305,U+0307-0308,U+0310,U+0312,U+0315,U+031A,U+0326-0327,U+032C,U+032F-0330,U+0332-0333,U+0338,U+033A,U+0346,U+034D,U+0391-03A1,U+03A3-03A9,U+03B1-03C9,U+03D1,U+03D5-03D6,U+03F0-03F1,U+03F4-03F5,U+2016-2017,U+2034-2038,U+203C,U+2040,U+2043,U+2047,U+2050,U+2057,U+205F,U+2070-2071,U+2074-208E,U+2090-209C,U+20D0-20DC,U+20E1,U+20E5-20EF,U+2100-2112,U+2114-2115,U+2117-2121,U+2123-214F,U+2190,U+2192,U+2194-21AE,U+21B0-21E5,U+21F1-21F2,U+21F4-2211,U+2213-2214,U+2216-22FF,U+2308-230B,U+2310,U+2319,U+231C-2321,U+2336-237A,U+237C,U+2395,U+239B-23B7,U+23D0,U+23DC-23E1,U+2474-2475,U+25AF,U+25B3,U+25B7,U+25BD,U+25C1,U+25CA,U+25CC,U+25FB,U+266D-266F,U+27C0-27FF,U+2900-2AFF,U+2B0E-2B11,U+2B30-2B4C,U+2BFE,U+3030,U+FF5B,U+FF5D,U+1D400-1D7FF,U+1EE00-1EEFF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '400',
    url: f69,
    unicodeRange:
      'U+0001-000C,U+000E-001F,U+007F-009F,U+20DD-20E0,U+20E2-20E4,U+2150-218F,U+2190,U+2192,U+2194-2199,U+21AF,U+21E6-21F0,U+21F3,U+2218-2219,U+2299,U+22C4-22C6,U+2300-243F,U+2440-244A,U+2460-24FF,U+25A0-27BF,U+2800-28FF,U+2921-2922,U+2981,U+29BF,U+29EB,U+2B00-2BFF,U+4DC0-4DFF,U+FFF9-FFFB,U+10140-1018E,U+10190-1019C,U+101A0,U+101D0-101FD,U+102E0-102FB,U+10E60-10E7E,U+1D2C0-1D2D3,U+1D2E0-1D37F,U+1F000-1F0FF,U+1F100-1F1AD,U+1F1E6-1F1FF,U+1F30D-1F30F,U+1F315,U+1F31C,U+1F31E,U+1F320-1F32C,U+1F336,U+1F378,U+1F37D,U+1F382,U+1F393-1F39F,U+1F3A7-1F3A8,U+1F3AC-1F3AF,U+1F3C2,U+1F3C4-1F3C6,U+1F3CA-1F3CE,U+1F3D4-1F3E0,U+1F3ED,U+1F3F1-1F3F3,U+1F3F5-1F3F7,U+1F408,U+1F415,U+1F41F,U+1F426,U+1F43F,U+1F441-1F442,U+1F444,U+1F446-1F449,U+1F44C-1F44E,U+1F453,U+1F46A,U+1F47D,U+1F4A3,U+1F4B0,U+1F4B3,U+1F4B9,U+1F4BB,U+1F4BF,U+1F4C8-1F4CB,U+1F4D6,U+1F4DA,U+1F4DF,U+1F4E3-1F4E6,U+1F4EA-1F4ED,U+1F4F7,U+1F4F9-1F4FB,U+1F4FD-1F4FE,U+1F503,U+1F507-1F50B,U+1F50D,U+1F512-1F513,U+1F53E-1F54A,U+1F54F-1F5FA,U+1F610,U+1F650-1F67F,U+1F687,U+1F68D,U+1F691,U+1F694,U+1F698,U+1F6AD,U+1F6B2,U+1F6B9-1F6BA,U+1F6BC,U+1F6C6-1F6CF,U+1F6D3-1F6D7,U+1F6E0-1F6EA,U+1F6F0-1F6F3,U+1F6F7-1F6FC,U+1F700-1F7FF,U+1F800-1F80B,U+1F810-1F847,U+1F850-1F859,U+1F860-1F887,U+1F890-1F8AD,U+1F8B0-1F8BB,U+1F8C0-1F8C1,U+1F900-1F90B,U+1F93B,U+1F946,U+1F984,U+1F996,U+1F9E9,U+1FA00-1FA6F,U+1FA70-1FA7C,U+1FA80-1FA89,U+1FA8F-1FAC6,U+1FACE-1FADC,U+1FADF-1FAE9,U+1FAF0-1FAF8,U+1FB00-1FBFF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '400',
    url: f70,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '400',
    url: f71,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '500',
    url: f72,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '500',
    url: f73,
    unicodeRange:
      'U+0302-0303,U+0305,U+0307-0308,U+0310,U+0312,U+0315,U+031A,U+0326-0327,U+032C,U+032F-0330,U+0332-0333,U+0338,U+033A,U+0346,U+034D,U+0391-03A1,U+03A3-03A9,U+03B1-03C9,U+03D1,U+03D5-03D6,U+03F0-03F1,U+03F4-03F5,U+2016-2017,U+2034-2038,U+203C,U+2040,U+2043,U+2047,U+2050,U+2057,U+205F,U+2070-2071,U+2074-208E,U+2090-209C,U+20D0-20DC,U+20E1,U+20E5-20EF,U+2100-2112,U+2114-2115,U+2117-2121,U+2123-214F,U+2190,U+2192,U+2194-21AE,U+21B0-21E5,U+21F1-21F2,U+21F4-2211,U+2213-2214,U+2216-22FF,U+2308-230B,U+2310,U+2319,U+231C-2321,U+2336-237A,U+237C,U+2395,U+239B-23B7,U+23D0,U+23DC-23E1,U+2474-2475,U+25AF,U+25B3,U+25B7,U+25BD,U+25C1,U+25CA,U+25CC,U+25FB,U+266D-266F,U+27C0-27FF,U+2900-2AFF,U+2B0E-2B11,U+2B30-2B4C,U+2BFE,U+3030,U+FF5B,U+FF5D,U+1D400-1D7FF,U+1EE00-1EEFF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '500',
    url: f74,
    unicodeRange:
      'U+0001-000C,U+000E-001F,U+007F-009F,U+20DD-20E0,U+20E2-20E4,U+2150-218F,U+2190,U+2192,U+2194-2199,U+21AF,U+21E6-21F0,U+21F3,U+2218-2219,U+2299,U+22C4-22C6,U+2300-243F,U+2440-244A,U+2460-24FF,U+25A0-27BF,U+2800-28FF,U+2921-2922,U+2981,U+29BF,U+29EB,U+2B00-2BFF,U+4DC0-4DFF,U+FFF9-FFFB,U+10140-1018E,U+10190-1019C,U+101A0,U+101D0-101FD,U+102E0-102FB,U+10E60-10E7E,U+1D2C0-1D2D3,U+1D2E0-1D37F,U+1F000-1F0FF,U+1F100-1F1AD,U+1F1E6-1F1FF,U+1F30D-1F30F,U+1F315,U+1F31C,U+1F31E,U+1F320-1F32C,U+1F336,U+1F378,U+1F37D,U+1F382,U+1F393-1F39F,U+1F3A7-1F3A8,U+1F3AC-1F3AF,U+1F3C2,U+1F3C4-1F3C6,U+1F3CA-1F3CE,U+1F3D4-1F3E0,U+1F3ED,U+1F3F1-1F3F3,U+1F3F5-1F3F7,U+1F408,U+1F415,U+1F41F,U+1F426,U+1F43F,U+1F441-1F442,U+1F444,U+1F446-1F449,U+1F44C-1F44E,U+1F453,U+1F46A,U+1F47D,U+1F4A3,U+1F4B0,U+1F4B3,U+1F4B9,U+1F4BB,U+1F4BF,U+1F4C8-1F4CB,U+1F4D6,U+1F4DA,U+1F4DF,U+1F4E3-1F4E6,U+1F4EA-1F4ED,U+1F4F7,U+1F4F9-1F4FB,U+1F4FD-1F4FE,U+1F503,U+1F507-1F50B,U+1F50D,U+1F512-1F513,U+1F53E-1F54A,U+1F54F-1F5FA,U+1F610,U+1F650-1F67F,U+1F687,U+1F68D,U+1F691,U+1F694,U+1F698,U+1F6AD,U+1F6B2,U+1F6B9-1F6BA,U+1F6BC,U+1F6C6-1F6CF,U+1F6D3-1F6D7,U+1F6E0-1F6EA,U+1F6F0-1F6F3,U+1F6F7-1F6FC,U+1F700-1F7FF,U+1F800-1F80B,U+1F810-1F847,U+1F850-1F859,U+1F860-1F887,U+1F890-1F8AD,U+1F8B0-1F8BB,U+1F8C0-1F8C1,U+1F900-1F90B,U+1F93B,U+1F946,U+1F984,U+1F996,U+1F9E9,U+1FA00-1FA6F,U+1FA70-1FA7C,U+1FA80-1FA89,U+1FA8F-1FAC6,U+1FACE-1FADC,U+1FADF-1FAE9,U+1FAF0-1FAF8,U+1FB00-1FBFF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '500',
    url: f75,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '500',
    url: f76,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '700',
    url: f77,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '700',
    url: f78,
    unicodeRange:
      'U+0302-0303,U+0305,U+0307-0308,U+0310,U+0312,U+0315,U+031A,U+0326-0327,U+032C,U+032F-0330,U+0332-0333,U+0338,U+033A,U+0346,U+034D,U+0391-03A1,U+03A3-03A9,U+03B1-03C9,U+03D1,U+03D5-03D6,U+03F0-03F1,U+03F4-03F5,U+2016-2017,U+2034-2038,U+203C,U+2040,U+2043,U+2047,U+2050,U+2057,U+205F,U+2070-2071,U+2074-208E,U+2090-209C,U+20D0-20DC,U+20E1,U+20E5-20EF,U+2100-2112,U+2114-2115,U+2117-2121,U+2123-214F,U+2190,U+2192,U+2194-21AE,U+21B0-21E5,U+21F1-21F2,U+21F4-2211,U+2213-2214,U+2216-22FF,U+2308-230B,U+2310,U+2319,U+231C-2321,U+2336-237A,U+237C,U+2395,U+239B-23B7,U+23D0,U+23DC-23E1,U+2474-2475,U+25AF,U+25B3,U+25B7,U+25BD,U+25C1,U+25CA,U+25CC,U+25FB,U+266D-266F,U+27C0-27FF,U+2900-2AFF,U+2B0E-2B11,U+2B30-2B4C,U+2BFE,U+3030,U+FF5B,U+FF5D,U+1D400-1D7FF,U+1EE00-1EEFF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '700',
    url: f79,
    unicodeRange:
      'U+0001-000C,U+000E-001F,U+007F-009F,U+20DD-20E0,U+20E2-20E4,U+2150-218F,U+2190,U+2192,U+2194-2199,U+21AF,U+21E6-21F0,U+21F3,U+2218-2219,U+2299,U+22C4-22C6,U+2300-243F,U+2440-244A,U+2460-24FF,U+25A0-27BF,U+2800-28FF,U+2921-2922,U+2981,U+29BF,U+29EB,U+2B00-2BFF,U+4DC0-4DFF,U+FFF9-FFFB,U+10140-1018E,U+10190-1019C,U+101A0,U+101D0-101FD,U+102E0-102FB,U+10E60-10E7E,U+1D2C0-1D2D3,U+1D2E0-1D37F,U+1F000-1F0FF,U+1F100-1F1AD,U+1F1E6-1F1FF,U+1F30D-1F30F,U+1F315,U+1F31C,U+1F31E,U+1F320-1F32C,U+1F336,U+1F378,U+1F37D,U+1F382,U+1F393-1F39F,U+1F3A7-1F3A8,U+1F3AC-1F3AF,U+1F3C2,U+1F3C4-1F3C6,U+1F3CA-1F3CE,U+1F3D4-1F3E0,U+1F3ED,U+1F3F1-1F3F3,U+1F3F5-1F3F7,U+1F408,U+1F415,U+1F41F,U+1F426,U+1F43F,U+1F441-1F442,U+1F444,U+1F446-1F449,U+1F44C-1F44E,U+1F453,U+1F46A,U+1F47D,U+1F4A3,U+1F4B0,U+1F4B3,U+1F4B9,U+1F4BB,U+1F4BF,U+1F4C8-1F4CB,U+1F4D6,U+1F4DA,U+1F4DF,U+1F4E3-1F4E6,U+1F4EA-1F4ED,U+1F4F7,U+1F4F9-1F4FB,U+1F4FD-1F4FE,U+1F503,U+1F507-1F50B,U+1F50D,U+1F512-1F513,U+1F53E-1F54A,U+1F54F-1F5FA,U+1F610,U+1F650-1F67F,U+1F687,U+1F68D,U+1F691,U+1F694,U+1F698,U+1F6AD,U+1F6B2,U+1F6B9-1F6BA,U+1F6BC,U+1F6C6-1F6CF,U+1F6D3-1F6D7,U+1F6E0-1F6EA,U+1F6F0-1F6F3,U+1F6F7-1F6FC,U+1F700-1F7FF,U+1F800-1F80B,U+1F810-1F847,U+1F850-1F859,U+1F860-1F887,U+1F890-1F8AD,U+1F8B0-1F8BB,U+1F8C0-1F8C1,U+1F900-1F90B,U+1F93B,U+1F946,U+1F984,U+1F996,U+1F9E9,U+1FA00-1FA6F,U+1FA70-1FA7C,U+1FA80-1FA89,U+1FA8F-1FAC6,U+1FACE-1FADC,U+1FADF-1FAE9,U+1FAF0-1FAF8,U+1FB00-1FBFF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '700',
    url: f80,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'David Libre',
    style: 'normal',
    weight: '700',
    url: f81,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Noto Serif Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f82,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Noto Serif Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f83,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Noto Serif Hebrew',
    style: 'normal',
    weight: '100 900',
    url: f84,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Secular One',
    style: 'normal',
    weight: '400',
    url: f85,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Secular One',
    style: 'normal',
    weight: '400',
    url: f86,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Secular One',
    style: 'normal',
    weight: '400',
    url: f87,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Suez One',
    style: 'normal',
    weight: '400',
    url: f88,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Suez One',
    style: 'normal',
    weight: '400',
    url: f89,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Suez One',
    style: 'normal',
    weight: '400',
    url: f90,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '300',
    url: f91,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '300',
    url: f92,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '300',
    url: f93,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '400',
    url: f94,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '400',
    url: f95,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '400',
    url: f96,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '700',
    url: f97,
    unicodeRange: 'U+0307-0308,U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '700',
    url: f98,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Karantina',
    style: 'normal',
    weight: '700',
    url: f99,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Inter',
    style: 'normal',
    weight: '100 900',
    url: f100,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Inter',
    style: 'normal',
    weight: '100 900',
    url: f101,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Inter',
    style: 'italic',
    weight: '100 900',
    url: f102,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Inter',
    style: 'italic',
    weight: '100 900',
    url: f103,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '100',
    url: f104,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '100',
    url: f105,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '100',
    url: f106,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '100',
    url: f107,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '200',
    url: f108,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '200',
    url: f109,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '200',
    url: f110,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '200',
    url: f111,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '300',
    url: f112,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '300',
    url: f113,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '300',
    url: f114,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '300',
    url: f115,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '400',
    url: f116,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '400',
    url: f117,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '400',
    url: f118,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '400',
    url: f119,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '500',
    url: f120,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '500',
    url: f121,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '500',
    url: f122,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '500',
    url: f123,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '600',
    url: f124,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '600',
    url: f125,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '600',
    url: f126,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '600',
    url: f127,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '700',
    url: f128,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '700',
    url: f129,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '700',
    url: f130,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '700',
    url: f131,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '800',
    url: f132,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '800',
    url: f133,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '800',
    url: f134,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '800',
    url: f135,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '900',
    url: f136,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'italic',
    weight: '900',
    url: f137,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '900',
    url: f138,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Poppins',
    style: 'normal',
    weight: '900',
    url: f139,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Montserrat',
    style: 'normal',
    weight: '100 900',
    url: f140,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Montserrat',
    style: 'normal',
    weight: '100 900',
    url: f141,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Montserrat',
    style: 'italic',
    weight: '100 900',
    url: f142,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Montserrat',
    style: 'italic',
    weight: '100 900',
    url: f143,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Manrope',
    style: 'normal',
    weight: '200 800',
    url: f144,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Manrope',
    style: 'normal',
    weight: '200 800',
    url: f145,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'DM Sans',
    style: 'normal',
    weight: '100 1000',
    url: f146,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'DM Sans',
    style: 'normal',
    weight: '100 1000',
    url: f147,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'DM Sans',
    style: 'italic',
    weight: '100 1000',
    url: f148,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'DM Sans',
    style: 'italic',
    weight: '100 1000',
    url: f149,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Space Grotesk',
    style: 'normal',
    weight: '300 700',
    url: f150,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Space Grotesk',
    style: 'normal',
    weight: '300 700',
    url: f151,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Playfair Display',
    style: 'normal',
    weight: '400 900',
    url: f152,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Playfair Display',
    style: 'normal',
    weight: '400 900',
    url: f153,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Playfair Display',
    style: 'italic',
    weight: '400 900',
    url: f154,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Playfair Display',
    style: 'italic',
    weight: '400 900',
    url: f155,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'DM Serif Display',
    style: 'italic',
    weight: '400',
    url: f156,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'DM Serif Display',
    style: 'italic',
    weight: '400',
    url: f157,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'DM Serif Display',
    style: 'normal',
    weight: '400',
    url: f158,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'DM Serif Display',
    style: 'normal',
    weight: '400',
    url: f159,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'JetBrains Mono',
    style: 'normal',
    weight: '100 800',
    url: f160,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'JetBrains Mono',
    style: 'normal',
    weight: '100 800',
    url: f161,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'JetBrains Mono',
    style: 'italic',
    weight: '100 800',
    url: f162,
    unicodeRange:
      'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'JetBrains Mono',
    style: 'italic',
    weight: '100 800',
    url: f163,
    unicodeRange:
      'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
];
