// Operations the catalogue leaves out on purpose (ADR-007): pure functions that compute
// commands from the catalogue. The editor (WG5-T06) and the Deck API share them.
export {
  alignElements,
  canReorder,
  distributeElements,
  groupElements,
  reorderElements,
  type AlignEdge,
  type ArrangeReference,
  type DistributeAxis,
  type ZOrderMove,
} from './arrange';
export {
  cloneElement,
  duplicateElements,
  duplicateSlide,
  type DuplicateElementsOptions,
  type DuplicateSlideOptions,
} from './duplicate';
export {
  assetsUsedBy,
  detachElements,
  pasteElements,
  pasteSlides,
  type PasteElementsOptions,
  type PasteSlidesOptions,
} from './clipboard';
export { slideFromLayout, type SlideFromLayoutOptions } from './layout';
export {
  batchFitted,
  refitAfter,
  refitAll,
  refitCommands,
  refitGroups,
  refitPatches,
  type Placement,
  type PlacementPatch,
} from './refit';
export {
  anchorOf,
  canMerge,
  canSplit,
  cellAt,
  cellBox,
  cellRange,
  cellText,
  clearCells,
  deleteCols,
  deleteRows,
  distributeCols,
  distributeRows,
  expandRange,
  flipDirection,
  fullRange,
  insertCols,
  insertRows,
  mergeCells,
  MIN_COL,
  MIN_ROW,
  neighbourCell,
  newTable,
  nextCell,
  pasteGrid,
  rangeCells,
  resizeColumn,
  resizedFrame,
  resizeRow,
  setBorders,
  spanOf,
  splitCells,
  tableFromGrid,
  tableSizes,
  tableText,
  updateCells,
  withRowHeights,
  type BorderEdges,
  type CellRange,
  type CellRef,
  type TablePatch,
} from './table';
