import { registerMessages } from '../i18n';

/* The strings of the shared controls (WG3-T06): the colour field and the font field. */
registerMessages('controls', {
  he: {
    color: {
      area: 'רוויה ובהירות',
      hue: 'גוון',
      alpha: 'אטימות',
      hex: 'קוד צבע',
      eyedropper: 'טפטפת',
      none: 'ללא צבע',
      recent: 'אחרונים',
      theme: 'צבעי התבנית',
    },
    token: {
      bg: 'רקע',
      surface: 'משטח',
      text: 'טקסט',
      muted: 'טקסט משני',
      primary: 'ראשי',
      secondary: 'משני',
      accent: 'הדגשה',
    },
    font: {
      search: 'חיפוש גופן',
      recent: 'אחרונים',
      all: 'כל הגופנים',
      deck: 'במצגת הזאת',
      mine: 'הגופנים שלי',
      library: 'ספריית Slidr',
      system: 'במחשב הזה',
      hebrew: 'תומך בעברית',
      empty: 'לא נמצא גופן כזה',
    },
    mixed: 'מעורב',
  },
  en: {
    color: {
      area: 'Saturation and brightness',
      hue: 'Hue',
      alpha: 'Opacity',
      hex: 'Hex code',
      eyedropper: 'Eyedropper',
      none: 'No colour',
      recent: 'Recent',
      theme: 'Theme colours',
    },
    token: {
      bg: 'Background',
      surface: 'Surface',
      text: 'Text',
      muted: 'Muted text',
      primary: 'Primary',
      secondary: 'Secondary',
      accent: 'Accent',
    },
    font: {
      search: 'Search fonts',
      recent: 'Recent',
      all: 'All fonts',
      deck: 'In this presentation',
      mine: 'My fonts',
      library: 'Slidr library',
      system: 'On this computer',
      hebrew: 'Supports Hebrew',
      empty: 'No font by that name',
    },
    mixed: 'Mixed',
  },
});
